stick:
  # Allows to set amount of damage on successful magic.
  # Items that cannot be damaged, like STICK, will be removed.
  # 0 means that damage will not be applied. 
  success-damage: 0
  # Allows to set amount of damage on failed magic.
  # Items that cannot be damaged, like STICK, will be removed.
  # 0 means that damage will not be applied. 
  error-damage: 0
cauldron:
  # Allows to toggle if extra ingredients should be dropped in cauldron.
  # Setting it to `true` will allow to perform magic only if items are dropped in cauldron.
  mix-in-cauldron: true
  # Allows to toggle if extra ingredients should be in correct count.
  # Setting it to `true` will fail any recipe where extras in cauldron are more then required.
  # This option works only if `mix-in-cauldron` is enabled.
  require-exact: false
  # Allows to toggle if left-overs for extra ingredients should be removed.
  # Setting it to `true` will remove all left-over ingredients that were dropped in cauldron.
  # This option works only if `mix-in-cauldron` is enabled and `require-exact` is disabled.
  remove-left-overs: false
  # Allows to toggle if items inside cauldron should be removed on failed magic.
  # Setting it to `true` will remove all items inside cauldron if magic fails.
  # This option works only if `mix-in-cauldron` is enabled.
  remove-on-fail: false
lightning:
  successful:
    # Allows to toggle lightning between visual and damage mode when recipe worked.
    # Setting it to `true` will summon actual lightning that will damage and set things on fire
    # Setting it to `false` will just make visual lightning and sound.
    damage: false
    # Allows to toggle lightning should target cauldron or player who performed successful magic.
    # Setting it to `true` will force lightning to target player.
    # Setting it to `false` will force lightning to target cauldron.
    hit-player: false
    # Allows to toggle lightning should destroy the cauldron after successful magic.
    # Setting it to `true` will force lightning to destroy cauldron.
    # Setting it to `false` will not allow lightning to destroy cauldron.
    destroy-cauldron: false
    # Allows to set the ticks daley between lightning strikes.
    # If left empty, lightning will not strike.
    timings:
      - 20
      - 30
      - 40
      - 50
  error:
    # Allows to toggle lightning between visual and damage mode when recipe did worked.
    # Setting it to `true` will summon actual lightning that will damage and set things on fire
    # Setting it to `false` will just make visual lightning and sound.
    damage: true
    # Allows to toggle lightning should target cauldron or player when magic failed.
    # Setting it to `true` will force lightning to target player.
    # Setting it to `false` will force lightning to target cauldron.
    hit-player: false
    # Allows to toggle lightning should destroy the cauldron after failed magic.
    # Setting it to `true` will force lightning to destroy cauldron.
    # Setting it to `false` will not allow lightning to destroy cauldron.
    destroy-cauldron: false
    # Allows to set the ticks daley between lightning strikes.
    # If left empty, lightning will not strike.
    timings:
      - 20
      - 40
      - 60
# 
# This list stores GameModes in which CauldronWitchery addon should not work.
# To disable addon it is necessary to write its name in new line that starts with -. Example:
# disabled-gamemodes:
#  - BSkyBlock
disabled-gamemodes: []
